config/routes.rb
Rails.application.routes.draw do
  resources :messages
  devise_for :users, controllers: { registrations: 'registrations',
                                    passwords: 'passwords' }

  get '/search' => 'search#index'

  get '/:username' => 'users#show'

  get '/:username/followers' => 'users#followers', as: 'followers_user'

  get '/:username/followings' => 'users#followings', as: 'followings_user'

  get '/:username/notifications' => 'users#notifications', as: 'notifications_user'

  post '/users/:username/follow' => 'users#follow', as: 'follow_user'

  root to: 'home#index'
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :following, class_name: "User"
  belongs_to :user

  validates :following, presence: true
  validates :following, uniqueness: { scope: :user }

  scope :by_following_id, ->(following_id) {
    where(following_id: following_id)
  }

  scope :by_user_id, ->(user_id) {
    where(user_id: user_id)
  }

  def to_s
    user.to_s
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user

  validates :content, presence: true

  scope :from_users, ->(user_ids) {
    where(arel_table[:user_id].in(user_ids))
  }

  scope :inverse, -> {
    order(arel_table[:created_at].desc)
  }

  def to_s
    content
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :follower

  validates :follower, presence: true

  scope :by_user_id, ->(user_id) {
    where(user_id: user_id)
  }

  scope :unread, -> {
    where(arel_table[:read].not_eq(true))
  }

  def read!
    update_column :read, true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :followers, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :username, presence: true, uniqueness: true

  def can_follow?(user_id)
    return if self.id == user_id

    Follower.by_following_id(user_id).empty?
  end

  def followed_by!(user)
    return unless can_follow?(user.id)

    self.followers.build(following_id: user.id)

    saved = self.save!

    if saved
      follower = Follower.by_following_id(user.id).first

      user.notifications.create!(follower_id: follower.id)
    end

    saved
  end

  def following_count
    Follower.by_following_id(id).count
  end

  def unread_notifications_count
    self.notifications.unread.count
  end

  def to_param
    username
  end

  def to_s
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout :handle_layout

  before_action :load_counters, only: :index
  before_action :load_messages, only: :index

  private

  def handle_layout
    if current_user.present?
      'application'
    else
      'external'
    end
  end

  def load_counters
    @user_count ||= User.count
    @message_count ||= Message.count
  end

  def load_messages
    if current_user.present?
      users = []

      followings = Follower.by_following_id(current_user.id).pluck(:user_id)

      users << current_user.id
      users = users + followings

      @messages = Message.from_users(users.uniq).inverse
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.user = current_user

    respond_to do |format|
      if @message.save
        format.js
      else
        format.js
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController
  before_action :configure_permitted_parameters

  protected

  def after_sending_reset_password_instructions_path_for(resource_name)
    root_path
  end

  def after_resetting_password_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :email
    devise_parameter_sanitizer.for(:account_update) << :password
    devise_parameter_sanitizer.for(:account_update) << :password_confirmation
    devise_parameter_sanitizer.for(:account_update) << :reset_password_token
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  skip_before_action :verify_authenticity_token, only: [:create]
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_up) << :email

    devise_parameter_sanitizer.for(:account_update) << :username
  end

  def after_sign_up_path_for(resource)
    root_path
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @users = User.where(username: params[:search][:q])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :follow
  before_action :user, only: :show
  before_action :load_messages, only: :show

  def follow
    if user.followed_by!(current_user)
      redirect_to :back, notice: "Nice, you follows #{user}!"
    end
  end

  def followers
    @followers = Follower.by_user_id(user.id)
  end

  def followings
    @followings = Follower.by_following_id(user.id).map(&:user)
  end

  def notifications
    @notifications = Notification.by_user_id(user.id)

    @notifications.each do |notification|
      notification.read!
    end
  end

  private

  def user
    @user ||= User.find_by!(username: params[:username])
  end

  def load_messages
    @messages = Message.from_users([user.id]).inverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_external.html.erb
<div class="section no-pad-bot deep-purple lighten-3">
  <div class="container">
    <h1 class="header center white-text">Microblog</h1>

    <div class="row center">
      <h4 class="header col s12 light center">Your own microblog, because your ideas can't be missed!</h4>
    </div>

    <div class="row center">
      <%= link_to "Let's go!", new_registration_path(:user), class: 'btn-large waves-effect waves-light' %>

      or

      <%= link_to "Sign in", new_session_path(:user), class: 'btn-large white deep-purple-text waves-effect waves-light' %>
    </div>

    <div class="row center">
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
    <div class="col s12">
      <h3 class="deep-purple-text text-lighten-3 center">Start search your friends now!</h3>

      <div class="nav-wrapper">
        <%= form_for(:search, url: search_path, method: :get) do |f| %>
          <div class="input-field input-search">
            <i class="material-icons">search</i>
            <%= f.text_field :q, value: (params.key?(:search) ? params[:search][:q] : '') %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/_inside.html.erb
<div class="row">
  <div class="col l3 s3">
    <%= render current_user %>
  </div>

  <div class="col l9 s9">
    <div class="col l12 s12">
      <%= render 'messages/form', message: Message.new %>
    </div>

    <div class="col l12 s12">
      <%= render @messages %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% if current_user.present? %>
  <%= render 'inside' %>
<% else %>
  <%= render 'external' %>
<% end %>

app/views/layouts/_flash.html.erb
<div class="row">
<% if alert %>
  <div class="col s12">
    <div class="alert alert-danger">
      <strong><i class="fa fa-bolt"></i></strong>

      <%= alert %>
    </div>
  </div>
<% end %>

<% if notice %>
  <div class="col s12">
    <div class="alert alert-success green lighten-4 green-text text-darken-2">
      <strong><i class="fa fa-check"></i></strong>

      <%= notice %>
    </div>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <title>Microblog</title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <header>
      <nav class="deep-purple lighten-2 custom-navbar white-text" role="navigation">
        <div class="container">
          <div class="nav-wrapper">
            <div class="logo-normal">
              <%= link_to 'Microblog', root_path, class: 'brand-logo left', id: 'logo-container' %>
            </div>

            <div class="logo-mobile">
              <%= link_to 'Microblog', root_path, class: 'brand-logo left', id: 'logo-container' %>
            </div>

            <div class="header-search">
              <%= form_for(:search, url: search_path, method: :get) do |f| %>
                <i class="material-icons">search</i>
                <%= f.text_field :q, value: (params.key?(:search) ? params[:search][:q] : '') %>
              <% end %>
            </div>

            <ul id="nav-mobile" class="right hide-on-med-and-down center header-items">
              <% if current_user.present? %>
                <li><%= current_user %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete  %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <div class="container">
        <%= render 'layouts/flash' %>

        <%= yield %>
      </div>
    </main>

    <footer class="page-footer deep-purple lighten-2">
      <div class="footer-copyright">
        <div class="container">
          © 2015 Microblog, All rights reserved.
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <title>Microblog</title>

    <%= stylesheet_link_tag 'application', media: 'all' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/external.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <title>Microblog</title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <main>
      <%= yield %>
    </main>
    <footer class="page-footer deep-purple lighten-2">
      <div class="container">
        <div class="row">
          <div class="col l4 s12">
            <h5 class="white-text">Join to our network</h5>

            <p class="grey-text text-lighten-4">
              Our network is growing and you will not want to miss out!
            </p>
          </div>

          <div class="col l4 s12">
            <h5 class="white-text">Some facts</h5>

            <p class="grey-text text-lighten-4">
              <%= @user_count %> users
            </p>

            <p class="grey-text text-lighten-4">
            <%= @message_count %> messages until now
            </p>
          </div>

          <div class="col l4 s12">
            <h5 class="white-text">Stay tuned!</h5>

            <ul class="fa-ul grey-text text-lighten-4">
              <li><%= fa_icon("facebook-official", class: "fa-li") %> /microblog</li>
              <li><%= fa_icon("google-plus-square", class: "fa-li") %> /+microblog</li>
            </ul>
          </div>
        </div>
      </div>

      <div class="footer-copyright">
        <div class="container">
          © 2015 Microblog, All rights reserved.
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(message, remote: true) do |f| %>
  <div class="col s10">
    <div id="error_explanation">
      <% if message.errors.any? %>
        <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

        <ul>
          <% message.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div class="field">
      <%= f.text_area :content, class: 'materialize-textarea' %>
    </div>
  </div>

  <div class="col s2">
    <div class="actions">
      <%= button_tag name: "action",
                    type: "submit",
                    class: "btn waves-effect waves-light btn-large", data: { disable_with: "Aguarde..." },
                    id: "send-message" do %>
        <%= fa_icon("check") %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-content">
    <span class="card-title grey-text"><%= message.user %></span>

    <p class="flow-text">
      <%= message.content %>
    </p>
  </div>
</div>

app/views/messages/create.js.erb
<% if @message.errors.any? %>
  $('#error_explanation').html('<%= escape_javascript(@message.errors.full_messages.to_sentence) %>');
<% end %>

app/views/search/index.html.erb
<% if @users.present? %>
  <% if @users.present? %>
    <%= render @users %>
  <% end %>
<% else %>
  <div class="row">
    <div class="col s12">
      <div class="card-panel center">
        <div class="row">
          <div class="col s12">
            <span class="flow-text">Nothing found!</span>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="col s12">
  <p>
  <%= user %>
  </p>

  <p>
  <%= user.email %>
  </p>

  <p>
  <%= link_to "#{user.followers.count} Followers", followers_user_path(user.username) %>
  </p>

  <p>
  <%= link_to "#{user.following_count} Followings", followings_user_path(user.username) %>
  </p>

  <% if current_user.present? && current_user == user %>
    <p>
    <%= link_to "#{user.unread_notifications_count} Notifications", notifications_user_path(user.username) %>
    </p>
  <% end %>

  <% if current_user.present? && current_user.can_follow?(user.id) %>
    <%= link_to 'Follow', follow_user_path(user.username), method: :post %>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="row">
<div class="col s3">
  <%= render @user %>
</div>

<div class="col l9 s9">
  <% if @followers.empty? %>
    <h4><%= @user %> does not have any follower yet!</h4>
  <% else %>
      <h5>
        <b><%= @user %> followers</b>
      </h5>
    <% @followers.each do |follower| %>
      <%= render follower.following %>
    <% end %>
  <% end %>
</div>
</div>

app/views/users/followings.html.erb
<div class="row">
<div class="col s3">
  <%= render @user %>
</div>

<div class="col l9 s9">
  <% if @followings.empty? %>
    <h4><%= @user %> does not have any user following yet!</h4>
  <% else %>
      <h5>
        <b><%= @user %> followings</b>
      </h5>
    <% @followings.each do |following| %>
      <%= render following %>
    <% end %>
  <% end %>
</div>
</div>

app/views/users/notifications.html.erb
<div class="row">
<div class="col s3">
  <%= render @user %>
</div>

<div class="col l9 s9">
  <% if @notifications.empty? %>
    <h4><%= @user %> does not have any notification!</h4>
  <% else %>
    <h5>
      <b><%= @user %> notifications</b>
    </h5>
    <% @notifications.each do |notification| %>
      <div class="row">
        <div class="col s12">
          <%= notification.follower %> follows you at <%= I18n.l(notification.created_at, format: :short) %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col l3 s3">
    <%= render @user %>
  </div>

  <div class="col l9 s9">
    <%= render @messages %>
  </div>
</div>